spring:
  data:
    mongodb:
      uri: mongodb://root:root@localhost:27017/appdatabase?authSource=admin
app:
  security:
    type: db

#  docker exec -it docker-mongodb-1 mongosh --username root --password root --authenticationDatabase admin
